### PR TITLE
feat-keyboard-shortcuts

### PR DESCRIPTION
**Pull request by tushartiwari7**
Added Feature
now, you can click on the buttons from their respective Keyboard buttons too which was previously only with mouse accesible.

### CODE REVIEW

**Comment by tushartiwari7** [comment]
please merge this pr if you liked and label this repo to hacktoberfest too.
because it is not counting against hacktoberfest submission yet. 😊

**Comment by Jookie262** [comment]
Hey men...i love your pull request..Gonna merge it

**Comment by Jookie262** [comment]
Hey men there's a problem..instead of divide..it shows a modulo

**Comment by tushartiwari7** [comment]
Thank you so much!
please add "hacktoberfest" label to the repo or "hacktoberfest-accepted" to my PR.
It will be really helpful

**Pull request merged**
